### ISSUE TITLE
Python3 Compatibility issues

### ISSUE THREAD

**Issue by nick-pateman-avalara** [passos/kong-cli#1]
Hi,

I've been trying to get kong-cli to run with Python3 and came across some issues.  I've got it compiling and executing now, the help output at least.  I'm yet to test the app itself (just about to), anyway, I've forked the repo with the changes in, just in-case you're interested.

Python isn't my primary language, so I wasn't going to just do a pull request.

https://github.com/nick-pateman-avalara/kong-cli/commit/4ef2ab2e4d075f43fa14240f87b76767bd1921bd

**Comment by passos** [comment]
Thanks for the comment. This tool was designed to work with Python 2. 
I don't have plan to maintain this tool at this moment. Please feel free to fork and improve it.
